[package]
name = "pay3"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
alloy-consensus = "1"
alloy-primitives = { version = "1", features = ["serde"] }
alloy-signer = "1"
alloy-signer-local = { version = "1", features = ["mnemonic"] }
async-trait = "0.1"
axum = { version = "0.8", features = ["macros"] }
base64 = "0.22"
bigdecimal = "0.4"
jsonwebtoken = "9"
redb = "4.1.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres", "migrate", "macros", "uuid", "time", "json", "bigdecimal"] }
thiserror = "2"
time = { version = "0.3", features = ["formatting", "macros", "parsing", "serde"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "time"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
uuid = { version = "1", features = ["serde", "v4"] }

[dev-dependencies]
http-body-util = "0.1"
tempfile = "3.27.0"
